# Generated by Django 2.2.4 on 2021-05-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20210523_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='books_authors_app.books'),
        ),
    ]
