# Generated by Django 2.2.4 on 2021-05-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='reglog.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reglog.Post')),
                ('user_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reglog.user')),
            ],
        ),
    ]
