# Generated by Django 2.2.4 on 2021-05-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0002_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='password',
        ),
    ]
