# Generated by Django 2.2.4 on 2021-05-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0003_remove_post_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_f',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
