# Generated by Django 2.2.4 on 2021-05-31 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thought', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_thoughts', to='reglog.user')),
                ('users', models.ManyToManyField(related_name='thoughts', to='reglog.user')),
            ],
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
