# Generated by Django 2.2.4 on 2021-05-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='users',
        ),
    ]
